# Generated by Django 4.2.6 on 2023-10-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('serving_size', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('kcal', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('carb', models.IntegerField()),
            ],
        ),
    ]
